main/urls.py
from django.urls import path
from . import views

app_name = "empl"

urlpatterns = [
    path('', views.empleados, name='index'),
    path('get/', views.obtener_empleados, name='get_empleados'),
    path('detalle/<int:id>/', views.empleado, name='detail_empleado'),
    path('update/<int:id>/', views.update_empleado, name='update_empleado'),
    path('save/', views.save_empleado, name='save_empleado'),
    path('delete/<int:id>/', views.delete_empleado, name='delete_empleado'),

#   Departamentos
    path('departamentos/', views.departamentos, name='deptos'),
    path('departamentos/detalle/<int:id>/', views.departamento, name='detail_depto'),
    path('departamentos/update/<int:id>/', views.update_departamento, name='update_depto'),
    path('departamentos/delete/<int:id>/', views.delete_departamento, name='delete_depto'),
    path('departamentos/save/', views.save_departamento, name='save_depto'),

#   Maquinas
    path('maquinarias/', views.maquinarias, name='maquinas'),
    path('maquinarias/detalle/<int:id>/', views.maquina, name='detail_maquina'),
    path('maquinarias/update/<int:id>/', views.update_maquina, name='update_maquina'),
    path('maquinarias/delete/<int:id>/', views.delete_maquina, name='delete_maquina'),
    path('maquinarias/save/', views.save_maquina, name='save_maquina'),

#   Proyectos
    path('proyectos/', views.proyectos, name='proyectos'),
    path('proyectos/detalle/<int:id>/', views.proyecto, name='detail_proyecto'),
    path('proyectos/update/<int:id>/', views.update_proyecto, name='update_proyecto'),
    path('proyectos/delete/<int:id>/', views.delete_proyecto, name='delete_proyecto'),
    path('proyectos/save/', views.save_proyecto, name='save_proyecto'),

#   TrabajaEn
    path('trabajaen/delete/<int:empleado_id>/', views.remove_trabajaen, name='remove_trabajaen'),

#   Familiar
    path('familiares/delete/<int:empleado_id>/', views.remove_familiar, name='remove_familiar'),

#   Reportes
    path('reporte/', views.reporte, name='reporte'),
    path('reporte/proyectos/', views.reporte_proyectos, name='reporte_proyectos'),
    path('reporte/departamentos/', views.reporte_departamentos, name='reporte_departamentos'),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('empleados/', include('main.urls')),
    path('admin/', admin.site.urls),

]

main/models.py
from django.db import models

# Create your models here.

class Empleado(models.Model):
	cedula = models.CharField(max_length=10)
	curp = models.CharField(max_length=18)
	nombre = models.CharField(max_length=255)
	apellidop = models.CharField(max_length=255)
	apellidom = models.CharField(max_length=255)
	sexo = models.CharField(max_length=1, choices=[('m', 'Mujer'), ('h', 'Hombre')])
	fechanac = models.DateField()
	salario = models.FloatField()
	issupervisor = models.BooleanField(default=False)
	supervisor = models.ForeignKey('Empleado', on_delete=models.SET_NULL, null=True, blank=True)

	def __str__(self):
		return "%s %s %s" % (self.nombre, self.apellidop, self.apellidom)

class Familiar(models.Model):

	PARENTESCOS = [
		('padre', 'Padre'),
		('madre', 'Madre'),
		('hijo', 'Hijo(a)'),
		('esposo', 'Esposo(a)'),
		('nieto', 'Nieto(a)'),
		('hermano', 'Hermano(a)'),
		('abuelo', 'Abuelo(a)'),
		('tio', 'Tio(a)'),
		('primo', 'Primo(a)'),
		('otro', 'Otro'),
	]

	empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
	curp = models.CharField(max_length=18)
	nombre = models.CharField(max_length=255)
	apellidop = models.CharField(max_length=255)
	apellidom = models.CharField(max_length=255)
	sexo = models.CharField(max_length=1, choices=[('m', 'Mujer'), ('h', 'Hombre')])
	parentesco = models.CharField(max_length=255, choices=PARENTESCOS)

	def __str__(self):
		return "%s %s %s" % (self.nombre, self.apellidop, self.apellidom)	

class Departamento(models.Model):
	nombre = models.CharField(max_length=255)
	
	def __str__(self):
		return self.nombre	

class Proyecto(models.Model):
	nombre = models.CharField(max_length=255)
	descripcion = models.CharField(max_length=255, null=True, blank=True)
	departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)

	def __str__(self):
		return self.nombre	

class Maquinaria(models.Model):
	ESTADOS = [
		('1', 'Disponible'),
		('2', 'Ocupado'),
	]
	descripcion = models.CharField(max_length=255)
	estatus = models.CharField(max_length=255, choices=ESTADOS)
	
	def __str__(self):
		return self.descripcion	

class TrabajaEn(models.Model):
	empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
	proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
	horas = models.IntegerField()

	def __str__(self):
		return self.empleado.nombre

class Jefe(models.Model):
	empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
	departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
	fechaads = models.DateField()

	def __str__(self):
		return self.empleado.nombre

class Asignado(models.Model):
	empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
	departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
	fechaads = models.DateField()

	def __str__(self):
		return self.empleado.nombre

class mAsignada(models.Model):
	ESTADOS = [
		('1', 'Disponible'),
		('2', 'Ocupado'),
	]
	proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
	maquinaria = models.ForeignKey(Maquinaria, on_delete=models.CASCADE)
	fechaa = models.DateField(auto_now_add=True)
	fechae = models.DateField(null=True, blank=True)
	estatus = models.CharField(max_length=255, choices=ESTADOS, default='1')

	def __str__(self):
		return self.proyecto.nombre

class Estado(models.Model):
	nombre = models.CharField(max_length=255)

	def __str__(self):
		return self.nombre

class Municipio(models.Model):
	nombre = models.CharField(max_length=255)
	
	def __str__(self):
		return self.nombre

class Direccion(models.Model):
	empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
	calle = models.CharField(max_length=255)
	colonia = models.CharField(max_length=255)
	localidad = models.CharField(max_length=255)
	cp = models.CharField(max_length=5)
	estado = models.ForeignKey(Estado, on_delete=models.SET_NULL, null=True, blank=True)
	municipio = models.ForeignKey(Municipio, on_delete=models.SET_NULL, null=True, blank=True)

	def __str__(self):
		return self.calle

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponse
from . import models as m
import json
from datetime import datetime
# Create your views here.
def response(data):
	if data:
		return JsonResponse({"success" : True, "data" : data})	
	return JsonResponse({"success" : False, "data" : []})	

def reporte(request):
	empleados = m.Empleado.objects.all()
	for e in empleados:
		e.proyectos = m.TrabajaEn.objects.filter(empleado=e)
		e.departamentos = m.Asignado.objects.filter(empleado=e)
		e.familiares = m.Familiar.objects.filter(empleado=e)
	ctx = {
		"data" : empleados,
		"qty" : len(empleados)
	}
	return render(request, 'main/reporte.html', ctx)

def reporte_proyectos(request):
	proyectos = m.Proyecto.objects.all()
	for p in proyectos:
		p.empleados = m.TrabajaEn.objects.filter(proyecto=p)
		p.maquinas = m.mAsignada.objects.filter(proyecto=p)
	ctx = {
		"data" : proyectos,
		"qty" : len(proyectos)
	}
	return render(request, 'main/reporte_proyectos.html', ctx)

def reporte_departamentos(request):
	departamentos = m.Departamento.objects.all()
	for d in departamentos:
		d.proyectos = m.Proyecto.objects.filter(departamento=d)
		d.empleados = m.Asignado.objects.filter(departamento=d)
		d.jefes = m.Jefe.objects.filter(departamento=d)
	ctx = {
		"data" : departamentos,
		"qty" : len(departamentos)
	}
	return render(request, 'main/reporte_departamentos.html', ctx)

def empleados(request):
	return render(request, 'main/empleados.html', {})

def empleado(request, id):
	empleado = get_object_or_404(m.Empleado, pk=id)
	empleado.salario = "%.2f" % empleado.salario or 0.00
	# empleado.sexo = 'Hombre' if empleado.sexo == 'h' else 'Mujer'
	jsone = {
				"id" : empleado.id,
				"nombre" : empleado.nombre,
				"apellidop" : empleado.apellidop,
				"apellidom" : empleado.apellidom,
				"cedula" : empleado.cedula,
				"curp" : empleado.curp,
				"sexo" : empleado.sexo,
				"fechanac" : str(empleado.fechanac),
				"salario" : empleado.salario,
				"supervisor" : ""
			}
	if empleado.supervisor:
		sup = empleado.supervisor
		jsone["supervisor"] = {
					"id" : sup.id,
					"full_name" : ("%s %s %s") % (sup.nombre, sup.apellidop, sup.apellidom),
					"nombre" : sup.nombre,
					"apellidop" : sup.apellidop,
					"apellidom" : sup.apellidom,
					"cedula" : sup.cedula,
					"curp" : sup.curp,
					"sexo" : sup.sexo,
					"fechanac" : str(sup.fechanac),
					"salario" : sup.salario,
					"supervisor" : ""
				} 
	familiares = m.Familiar.objects.filter(empleado=empleado).order_by('nombre')
	jsonf = []
	for e in familiares:
		jsonf.append({			
			"id" : e.id,
			"curp" : e.curp,
			"nombre" : e.nombre,
			"apellidop" : e.apellidop,
			"apellidom" : e.apellidom,
			"sexo" : e.sexo,
			"parentesco" : e.parentesco,
			})
	asignados = m.Asignado.objects.filter(empleado=empleado);
	jsona = []
	for e in asignados:
		jsona.append({			
			"id" : e.id,			
			"fechaads" : str(e.fechaads),
			"departamento" : {
					"id" : e.departamento.id,
					"nombre" : e.departamento.nombre,
				}
			})
	trabajaen = m.TrabajaEn.objects.filter(empleado=empleado)
	jsont = []
	for e in trabajaen:
		jsont.append({			
			"id" : e.id,			
			"horas" : e.horas,
			"proyecto" : {
				"id" : e.proyecto.id,
				"nombre" : e.proyecto.nombre,
				# "descripcion" : e.proyecto.descripcion,
				"departamento" : {
						"id" : e.proyecto.departamento.id,
						"nombre" : e.proyecto.departamento.nombre,
					}
				}
			})
	
	deptos = m.Departamento.objects.all().order_by('nombre')
	lista = []
	for d in deptos:
		lista.append({
			"id" : d.id,
			"nombre" : d.nombre,
			})

	proyectos = m.Proyecto.objects.all().order_by('nombre')
	listap = []
	for p in proyectos:
		listap.append({
			"id" : p.id,
			"nombre" : p.nombre,
			})
	empleados = get_empleados_list()
	ctx = {
		"e" : empleado,
		"json" : json.dumps(jsone), 
		"familiares" : json.dumps(jsonf), 
		"departamentos" : json.dumps(jsona), 
		"deptos_list" : json.dumps(lista), 
		"proyectos" : json.dumps(jsont), 
		"proyectos_list" : json.dumps(listap), 
		"empleados_list" : json.dumps(empleados), 
	}
	return render(request, 'main/empleado.html', ctx)

def update_empleado(request, id):
	if request.method == 'POST':
		datajson = json.loads(request.body.decode('utf-8'))
		print("#####")
		print(datajson)
		if "key" in datajson and "value" in datajson:
			empleado = get_object_or_404(m.Empleado, pk=id)
			value = datajson["value"]
			if datajson['key'] == 'departamento' and value:
				depto = get_object_or_404(m.Departamento, pk=value)
				asignaciones = m.Asignado.objects.filter(empleado=empleado)
				asignaciones.delete()
				fecha = datetime.now().strftime("%Y-%m-%d")
				nueva = m.Asignado(empleado=empleado, departamento=depto, fechaads=fecha)
				nueva.save()				
				return JsonResponse({"success" : True, "data" : {"departamento" : {"id" : depto.id, "nombre" : depto.nombre}, "fechaads" : fecha }})
			elif datajson['key'] == 'proyecto' and value:
				proyecto = get_object_or_404(m.Proyecto, pk=value)
				trabajaen = m.TrabajaEn.objects.filter(empleado=empleado).filter(proyecto=proyecto)
				if not trabajaen:
					nuevoproyecto = m.TrabajaEn(empleado=empleado, proyecto=proyecto, horas=0)
					nuevoproyecto.save()
					return JsonResponse({"success" : True, "data" : {"id" : nuevoproyecto.id, "horas" : 0, "proyecto" : {"id" : proyecto.id, "nombre" : proyecto.nombre}}})
			elif datajson['key'] == 'familiar' and value:				
				datajson["value"]["empleado_id"] = empleado.id
				familiar = m.Familiar.objects.create(**datajson["value"])				
				# familiar.save()
				return JsonResponse({"success" : True, "data" : datajson["value"]})
			elif datajson['key'] == 'supervisor' and value:				
				sup = get_object_or_404(m.Empleado, pk=int(value))
				empleado.supervisor= sup;
				empleado.save()
				return JsonResponse({"success" : True, "data" : datajson["value"]})			
			else:
				setattr(empleado, datajson["key"], value)			
				empleado.save()			
			return JsonResponse({"success" : True})
	return JsonResponse({"success" : False})

def save_empleado(request):
	if request.method == 'POST':
		datajson = json.loads(request.body.decode('utf-8'))
		if "nombre" in datajson and "apellidop" in datajson and "apellidom" in datajson and "cedula" in datajson and "curp" in datajson and "sexo" in datajson and "fechanac" in datajson:
			empleado = m.Empleado.objects.create(**datajson)
			# empleado = m.Empleado(nombre=datajson["nombre"], apellidop=datajson["apellidop"], apellidom=datajson["apellidom"], cedula=datajson["cedula"], curp=datajson["curp"], fechanac=datajson["fechanac"], sexo=datajson["sexo"])
			empleado.save()
			datajson["id"] = empleado.id
			return JsonResponse({"success" : True, "data" : datajson})
	return JsonResponse({"success" : False})

def delete_empleado(request, id):
	empleado = get_object_or_404(m.Empleado, pk=id)
	empleado.delete();
	return JsonResponse({"success" : True})

def get_empleados_list():
	empleados = m.Empleado.objects.all().order_by('nombre')
	data = []
	if empleados:
		for e in empleados:
			supervisor = ""
			if e.supervisor:
				supervisor =  {
					"id" : e.supervisor.id,
					"nombre" : "%s %s %s" % (e.supervisor.nombre, e.supervisor.apellidop, e.supervisor.apellidom),
				}
			data.append({
				"id" : e.id,
				"full_name" : ("%s %s %s") % (e.nombre, e.apellidop, e.apellidom),
				"nombre" : e.nombre,
				"apellidop" : e.apellidop,
				"apellidom" : e.apellidom,
				"cedula" : e.cedula,
				"curp" : e.curp,
				"sexo" : e.sexo,
				"fechanac" : str(e.fechanac),
				"salario" : "%.2f" % e.salario or 0.00,
				"supervisor" : supervisor			
			})
	return data

def obtener_empleados(request):	
	data = get_empleados_list()
	return response(data)

#### DEPARTAMENTOS ####

def departamentos(request):
	data = m.Departamento.objects.all().order_by('nombre')
	lista = []
	for d in data:
		lista.append({
			"id" : d.id,
			"nombre" : d.nombre
			})
	empleados = get_empleados_list()
	print(empleados)
	ctx = {
		"data" : json.dumps(lista),
		"empleados" : json.dumps(empleados)
	}
	return render(request, "main/departamentos.html", ctx)

def departamento(request, id):
	depto = get_object_or_404(m.Departamento, pk=id)
	jsone = {
				"id" : depto.id,
				"nombre" : depto.nombre,
				"jefe" : {}			
			}
	jefes = m.Jefe.objects.filter(departamento=depto)
	if jefes:
		emp = jefes[0].empleado
		jsone["jefe"] = {						
						"id" : jefes[0].empleado.id,
						"nombre" : "%s %s %s" % (emp.nombre, emp.apellidop, emp.apellidom),
						"apellidop" : jefes[0].empleado.apellidop,
						"apellidom" : jefes[0].empleado.apellidom,
						"cedula" : jefes[0].empleado.cedula,
						"curp" : jefes[0].empleado.curp,
						"sexo" : jefes[0].empleado.sexo,
						"fechanac" : str(jefes[0].empleado.fechanac),
						"salario" : "%.2f" % jefes[0].empleado.salario or 0.00,
						# "supervisor" : jefes[0].empleado.supervisor or '',						
					}
	jefes = m.Empleado.objects.all().order_by("nombre")
	jsonj = []
	for j in jefes:
		jsonj.append({
					"id" : j.id,
					"nombre" : "%s %s %s" % (j.nombre, j.apellidop, j.apellidom),					
					"apellidop" : j.apellidop,
					"apellidom" : j.apellidom,
					"cedula" : j.cedula,
					"curp" : j.curp,
					"sexo" : j.sexo,
					"fechanac" : str(j.fechanac),
					"salario" : "%.2f" % j.salario or 0.00,
					# "supervisor" : j.supervisor or '',
				}
			)	

	proyectos = m.Proyecto.objects.filter(departamento=depto)	
	jsonp = []	
	for p in proyectos:
		jsonp.append({
			"id" : p.id,
			"nombre" : p.nombre,
			# "descripcion" : p.descripcion,
			})
	empleados = m.Asignado.objects.filter(departamento=depto)
	jsonm = []
	for e in empleados:
		jsonm.append({
			"id" : e.empleado.id,
			"nombre" : "%s %s %s" % (e.empleado.nombre, e.empleado.apellidop, e.empleado.apellidom),
			# "apellidop" : m.empleado.apellidop,
			# "apellidom" : m.empleado.apellidom,
			})
			
	ctx = {
		"e" : depto,
		"json" : json.dumps(jsone), 
		"jefes" : json.dumps(jsonj), 

main/templates/main/departamento.html
{% extends 'main/index.html' %}
{% load static %}
{% block styles %}
<style>
	.editable:hover{
		cursor: pointer;
	}
	.hidden
	{
		display: none;
	}
	.editable:hover::after{
		display: inline-block;
	    font-style: normal;
	    font-variant: normal;
	    text-rendering: auto;
	    font-size: 15px;
	    -webkit-font-smoothing: antialiased;
		font-family: "Font Awesome 5 Free"; font-weight: 900; content: "\f303";
	}
</style>
{% endblock %}

{% block content %}

<div class="container-fluid" id="app">
	<br>
	<div class="row">		
		<div class="col-5 offset-1">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">Datos del Departamento</h5>
					<hr>
					<div class="card-text">
						<div class="row">
							<div class="col">
								Nombre:								
								<inline-editor :clave="'nombre'" :row="departamento"></inline-editor>
								
							</div>
						</div>
						<div class="row">
							<div class="col">
								Jefe:								
								<inline-editor :input="'select'" :clave="'jefe'" :field="'nombre'" :row="departamento" :options="jefes"></inline-editor>
							</div>
						</div>
					</div>					
				</div>
			</div>
		</div>
		<div class="col-5">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">Empleados</h5>
					<hr>
					<div class="card-text">
						<ul class="list-group">
						  <li v-for="item in empleados" class="list-group-item">
							<div class="row">
								<div class="col-12">
									<a :href="getUrl('/detalle/', item.id)">
									[[ item.nombre ]]</a>
									<!-- <span class="float-right">
										<small class="text-muted">Horas: </small><span class="badge badge-primary">[[item.horas]]</span>
									</span> -->
								</div>
							</div>
						  </li>						  
						</ul>
					</div>
				</div>
			</div>
			<br>
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">Proyectos</h5>
					<hr>
					<div class="card-text">
						<ul class="list-group">
						  <li v-for="item in proyectos" class="list-group-item">
							<div class="row">								
								<div class="col-12">
									<a :href="getUrl('/proyectos/detalle/', item.id)">[[ item.nombre ]]</a>
								</div>
							</div>
						  </li>						  
						</ul>
					</div>
				</div>
			</div>
			<br>
		</div>
	</div>
	<br>
</div>

{% endblock %}

{% block scripts %}
<script>
	let token = "{{csrf_token}}";	
</script>
<script src="{% static 'main/js/components/inline-editor.js' %}"></script>
<script>		
	
	let vm = new Vue({
		el : "#app",
		delimiters : ['[[', ']]'],
		data : {		
			departamento : JSON.parse('{{ json|safe }}'),
			jefes : JSON.parse('{{ jefes|safe }}'),
			proyectos : JSON.parse('{{ proyectos|safe }}'),
			empleados : JSON.parse('{{ empleados|safe }}'),
			host : 'http://localhost',
			module : '/departamentos',
			selected : [],						
		},
		computed : {
			getJefe : function(){
				let jefe = this.departamento.jefe;
				return jefe.nombre;
			}
		},
		methods : {
			isChecked : function(id){			
				return this.selected.indexOf(id) >= 0;
			},
			showModal : function(){

			},
			remove : function(){

			},
			isDisabled : function()
			{

			},
			getUrl : function(path, id){
				let url = this.host + path;
				if (id != undefined)
					url += id;
				return url;
			},
			select : function(id){
				let index = this.selected.indexOf(id);
				if(index < 0)
				{
					this.selected.push(id);
				}
				else
				{
					this.selected.splice(index, 1);	
				}
			},
		}
	})
</script>
{% endblock %}

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Empleados</title>
	<link rel="stylesheet" href="{% static '/main/css/bootstrap.min.css' %}">	
	<link rel="stylesheet" href="{% static '/main/css/fontawesome.css' %}">	
	<style>
		body
		{
			background-color: #f3f3f3;
		}		
	</style>
	{% block styles %}

	{% endblock %}
</head>
<body>
	{% block navbar %}
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="{% url 'empl:index' %}">Empleados</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbar">
			<ul class="navbar-nav mr-auto">
			  <li class="nav-item active">
			    <a class="nav-link" href="{% url 'empl:index' %}">Empleados</a>
			  </li>
			  <li class="nav-item active">
			    <a class="nav-link" href="{% url 'empl:deptos' %}">Departamentos</a>
			  </li>
			  <li class="nav-item active">
			    <a class="nav-link" href="{% url 'empl:maquinas' %}">Maquinas</a>
			  </li>			  
			  <li class="nav-item active">
			    <a class="nav-link" href="{% url 'empl:proyectos' %}">Proyectos</a>
			  </li>	
			  <li class="nav-item dropdown">
		        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          Reportes
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		          <a class="dropdown-item" href="{% url 'empl:reporte' %}">Reporte General Empleados</a>
		          <a class="dropdown-item" href="{% url 'empl:reporte_departamentos' %}">Reporte General Departamentos</a>
		          <a class="dropdown-item" href="{% url 'empl:reporte_proyectos' %}">Reporte General Proyectos</a>
		        </div>
		      </li>		  
			</ul>			
		</div>
	</nav>
	{% endblock %}
	{% block content%}
	<div class="container" id="app">
		<br>
		<div class="card">
			<div class="card-body">		
			
				<div class="row">
					<div class="col-md-4 col-12">
						
					</div>
				</div>
				
			</div> <!-- END CARD BODY -->
		</div>
	</div>
	{% endblock %}
	<script src="{% static '/main/js/jquery.min.js' %}"></script>
	<script src="{% static '/main/js/popper.min.js' %}"></script>
	<script src="{% static '/main/js/bootstrap.min.js' %}"></script>
	<script src="{% static '/main/js/vue.js' %}"></script>
	{% block scripts %}
	<script>
		let vm = new Vue({
			el : "#app",
			delimiters : ['[[', ']]'],
			data : {},
		})
	</script>
	{% endblock %}
</body>
</html>

main/templates/main/proyecto.html
{% extends 'main/index.html' %}
{% load static %}

{% block styles %}
<style>
	.editable:hover{
		cursor: pointer;
	}
	.hidden
	{
		display: none;
	}
	.editable:hover::after{
		display: inline-block;
	    font-style: normal;
	    font-variant: normal;
	    text-rendering: auto;
	    font-size: 15px;
	    -webkit-font-smoothing: antialiased;
		font-family: "Font Awesome 5 Free"; font-weight: 900; content: "\f303";
	}
</style>
{% endblock %}

{% block content %}

<div class="container" id="app">
	<br>
	<div class="row">		
		<div class="col-5 offset-1">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">Datos del Proyecto</h5>
					<hr>
					<div class="card-text">
						<div class="row">
							<div class="col">
								Nombre:								
								<inline-editor :clave="'nombre'" :row="proyecto"></inline-editor>
							</div>
						</div>
						<div class="row">
							<div class="col">
								Descripción:								
								<inline-editor :tipo="'p'" :input="'textarea'" :clave="'descripcion'" :row="proyecto"></inline-editor>
							</div>
						</div>
						<div class="row">
							<div class="col">
								Departamento:								
								<div class="row">
									<div class="col-12">
										<inline-editor :input="'select'" :clave="'departamento'" :field="'nombre'" :row="proyecto" :options="deptos.data"></inline-editor>
									</div>
								</div>
							</div>
						</div>
					</div>					
				</div>
			</div>
		</div>
		<div class="col-5">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">Empleados</h5>
					<hr>
					<div class="card-text">
						<ul class="list-group">
						  <li v-for="item in empleados" class="list-group-item">
							<div class="row">								
								<div class="col-12">
									<a :href="getUrl('/detalle/', item.id)">[[ item.nombre ]]</a>
									<span class="float-right">
										<small class="text-muted">Horas: </small><span class="badge badge-primary">[[item.horas]]</span>
									</span>
								</div>
							</div>
						  </li>						  
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br>
</div>

{% endblock %}

{% block scripts %}
<script>
	let token = "{{csrf_token}}";	
</script>
<script src="{% static 'main/js/components/inline-editor.js' %}"></script>
<script>
	// let jsondata = JSON.parse(`{{ json|safe }}`);
	let vm = new Vue({
		el : "#app",
		delimiters : ['[[', ']]'],
		data : {		
			proyecto : JSON.parse(`{{ json|safe }}`),
			deptos : JSON.parse(`{{ deptos|safe }}`),
			empleados : JSON.parse(`{{ empleados|safe }}`),
			host : 'http://localhost',						
			module : '/proyectos',						
		},
		methods : {
			editarDepto : function(){

			},
			getUrl : function(path, id){
				let url = this.host + path;
				if (id != undefined)
					url += id;
				return url;
			},
		}
	})
</script>
{% endblock %}